### ISSUE TITLE
Launching the AppImage gives an error

### ISSUE THREAD

**Issue by jordanamr** [SpacingBat3/ReForged#3]
```
$ chmod +x Arena\ Returns\ Launcher-1.0.5-SNAPSHOT-x64.AppImage
$ ./Arena\ Returns\ Launcher-1.0.5-SNAPSHOT-x64.AppImage
/tmp/.mount_Arena WAWNn4/usr/bin//arena-returns-launcher: line 2: /tmp/.mount_Arena WAWNn4/usr/bin//../lib/arena-returns-launcher/arena-returns-launcher: No such file or directory
```
Code used: https://github.com/ArenaReturns/Launcher/ (branch master, yarn install && yarn make)
AppImage file: https://transfer.sh/MLVImL/Arena%20Returns%20Launcher-1.0.5-SNAPSHOT-x64.AppImage

Thanks in advance and Merry Christmas !

**Comment by SpacingBat3** [comment]
@jordanamr I believe the `name` property of the AppImage maker config shouldn't be set in your case, I think I use it to point to binary rather than rename the binary itself… That's probably bad assumption through, given makers should have an access to the resolved config, so `name` would be useless if maker would just look at `name` in package config (althrough, I'm not sure if that's always the actual binary name – maybe cmdline or env flags could replace it?)…

Also I believe this is how official makers worked on Linux? At least I had to set `name` once I changed it in `packageConfig`, as they used `productName` by the default and basically ignored `packageConfig.name`…

Not sure if I should fix that if it the same logic might be in official makers for `.deb` or `.rpm`…

**Comment by jordanamr** [comment]
Interesting behaviour...
I assumed name would set set the binary name, not a big deal for an AppImage though, I'll try removing the property and see if it works

**Comment by jordanamr** [comment]
@SpacingBat3 It seems like specifying no name use the package.json name which wouldn't work in my case because of the organization format.
```
An unhandled rejection has occurred inside Forge:
Error: ENOENT: no such file or directory, copyfile './src/assets/icon/icon.png' -> '/tmp/.Arena Returns Launcher-1.0.5-SNAPSHOT-x64-taDGwC/@arenareturns/launcher.png'
```

**Comment by SpacingBat3** [comment]
@jordanamr I'll take a look how it is with official makers, I aim for making it similarly configurable, at least in case of Linux makers. But given I saw a lot of *defaults* to `name` in `package.json`, I feel that you might get a bit more trouble than normally, unless it is normally `basename`-d in Electron Forge.

**Comment by SpacingBat3** [comment]
@jordanamr Actually I see official makers sanitize the name if they need to do so, I guess nothing blocks me from doing the same…
If you're fine with that, I will also close this issue once name sanitization will make it to the `master` (that'll be soon).

**Comment by SpacingBat3** [comment]
Given I've implemented `name` sanitization at cae431b as well as updated the type definitions and `Readme.md` to actually make it less confusing what maker uses `name` for, I think this issue has been resolved.

**Comment by jordanamr** [comment]
Hello @SpacingBat3, I'm still having the run issues on 3.0.2.
The package.json "name" is not sanitized, and if I change the "name" config value for reforged, it generates a run script that starts the "name" executable, and it won't work because it seems like the executable name always use the top level "productName" (the one below my package.json "name")...
I've tried tweaking settings for the past 30 minutes and still can't get appimage to work, am I doing something wrong ?
Repo : https://github.com/ArenaReturns/Launcher/

**Comment by SpacingBat3** [comment]
@jordanamr Fixing bugs attempt `#3`… 😓️

Things now should improve much, since I've introduced `bin`. It fallbacks to `sanitized<options.name>` ~~→ `productName`~~ → `sanitized<name>`. ~~As I believe `productName` is used by the default as a binary name, this should provide more sane defaults.~~

**EDIT**: Looks like Electron makers doesn't actually care much about the defaults, I guess I will do the same and use `name` directly as a fallback. I will also check if `bin` actually exists and throw an error if not…

**Comment by jordanamr** [comment]
That sounds perfect! I'll try a little bit later to see if it's fixed for me.
Thank you very much for your patience and your time!!

**Comment by jordanamr** [comment]
Well, the appimage now builds properly, but my issue is that it cannot launch the executable because it contains spaces. However, if I want to build without spaces, that would also means all of my executables will lose spaces (including shortcuts on windows for example).
The cause is the .desktop file not able to launch the executable because it contains spaces, do you know a way to make it work ?

EDIT: After removing the space to try, It seems like it won't even run, it looks for :
`/tmp/.mount_ArenaRmuyCY5/usr/bin/lib/arena-returns-launcher/ArenaReturnsLauncher`
which is non-existent in the appimage, it's either `/usr/bin/ArenaReturnsLauncher` or `/usr/lib/arena-returns-launcher/ArenaReturnsLauncher`

**Comment by jordanamr** [comment]
Hello !
I've seen that you pushed 3.1.4, so I tried using these appimage maker settings:
```
"name": "arena-returns-launcher",
 "bin": "Arena Returns Launcher",
```

It seems like it generates everything correctly, but it does not interpret the double quotes properly in the .desktop, when running the appimage:
Error: Error executing '"Arena Returns Launcher"': No such file or directory

We're getting close!
Thanks for your amazing open source hard work.

**Comment by jordanamr** [comment]
Hello @SpacingBat3 !

I've seen that you pushed 3.1.4, so I tried using these appimage maker settings:
```
"name": "arena-returns-launcher",
 "bin": "Arena Returns Launcher",
```

It seems like it generates everything correctly, but it does not interpret the double quotes properly in the .desktop, when running the appimage:
`Error: Error executing '"Arena Returns Launcher"': No such file or directory`

We're getting close!
Thanks for your amazing open source hard work.

**Comment by JustSch** [comment]
> ```
> $ chmod +x Arena\ Returns\ Launcher-1.0.5-SNAPSHOT-x64.AppImage
> $ ./Arena\ Returns\ Launcher-1.0.5-SNAPSHOT-x64.AppImage
> /tmp/.mount_Arena WAWNn4/usr/bin//arena-returns-launcher: line 2: /tmp/.mount_Arena WAWNn4/usr/bin//../lib/arena-returns-launcher/arena-returns-launcher: No such file or directory
> ```
> 
> Code used: https://github.com/ArenaReturns/Launcher/ (branch master, yarn install && yarn make) AppImage file: https://transfer.sh/MLVImL/Arena%20Returns%20Launcher-1.0.5-SNAPSHOT-x64.AppImage
> 
> Thanks in advance and Merry Christmas !

I have this same issue with my project https://github.com/JustSch/ScratchJr-Desktop/tree/add-appimage where I have name, bin and product name in my forge config set to match my package.json but upon launching in terminal it says 
```
/tmp/.mount_ScratcAfmkSi/usr/bin//ScratchJr: 2: Syntax error: redirection unexpected. 
```
I also noticed upon extracting the appimage that the folder name in /usr/lib is truncated to cratchjr instead of scratchjr as well as both the icon and X-AppImage-Name in the .desktop file

**Comment by SpacingBat3** [comment]
> It seems like it generates everything correctly, but it does not interpret the double quotes properly in the .desktop, when running the appimage:
> ```
> Error: Error executing '"Arena Returns Launcher"': No such file or directory
> ```

@jordanamr Sorry for the late reply, I can't do anything about it unless I will decide to switch to non-binary / custom AppRun (ReForged currently downloads and validates the one provided by `AppImageKit`). I guess that's the upstream bug I won't work on (`xdg-open` parses `.desktop` file fine), but maybe it has been already fixed in like `continuous` version and might land alongside the next `AppImageKit` release.

**Comment by SpacingBat3** [comment]
> I also noticed upon extracting the appimage that the folder name in /usr/lib is truncated to cratchjr instead of scratchjr as well as both the icon and X-AppImage-Name in the .desktop file

The `name` entry is expected to be lowercase, but surely you found a flaw in the sanitizer.

>
> ```
> /tmp/.mount_ScratcAfmkSi/usr/bin//ScratchJr: 2: Syntax error: redirection unexpected.
> ```

Could you at least share the contents of the generated shell script and expected name of the binary?

**Comment by JustSch** [comment]
What do you mean by generated shell script? would this be in the app image or generated before then? I have also attempted running it with the name set to all lowercase in the package.json with no name set in the forge config and had the same result as above but the folders  as well as both the icon and X-AppImage-Name in the .desktop file have the correct name this time. If you mean the binary in the folder it generates before it makes the appimage it is called ScratchJr in both of these attempts so it probably set by the productName in my package.json. I do have "bin"="ScratchJr" set in the forge config. If by generated shell script you mean the script in /usr/bin of the appimage during the first attempt with the capital letters it contains:
```
#!/bin/sh
USR="$(sed 's/\/\/*/\//g;s/\/$//;s/\/[^/]*\/[^/]*$//' <<< "$0")"
exec "$USR/lib/cratchjr/ScratchJr" "$@"
```
and the second attempt with the all lowercase name in package.json:
```
#!/bin/sh
USR="$(sed 's/\/\/*/\//g;s/\/$//;s/\/[^/]*\/[^/]*$//' <<< "$0")"
exec "$USR/lib/scratchjr/ScratchJr" "$@"
```

**Comment by SpacingBat3** [comment]
@JustSch I've updated both the sanitizer (it's now in external module and even more generic/featured) and shell generation, both of your mentioned issue should be now fixed.

**Comment by JustSch** [comment]
after updating to the newest version of maker-appimage with npm I get the error
```
An unhandled rejection has occurred inside Forge:
Error: Could not find module with name '@reforged/maker-appimage'. If this is a package from NPM, make sure it's listed in the devDependencies of your package.json. If this is a local module, make sure you have the correct path to its entry point. Try using the DEBUG="electron-forge:require-search" environment variable for more information.
```
I do have it in the devDependencies of my package.json and have even tried deleting my node_modules and package-lock.json and rerunning npm install but the issue still happens so unfortunately I can't even see if your fixes fixed the original issue

**Comment by SpacingBat3** [comment]
@JustSch Try to update dependencies again (or at least `@spacingbat3/lss`), I've fixed a typo in `package.json`.

**Comment by JustSch** [comment]
Thank both issues seemed to be fixed now and I was able to build a successfully working appimage ☺️
